"""Change id_value and id33_value to bytea

Revision ID: 0f81d5ade905
Revises: 47c6a73ea6f5
Create Date: 2025-02-19 11:07:06.324535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f81d5ade905'
down_revision: Union[str, None] = '47c6a73ea6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
