"""Change id_value and id33_value to bytea

Revision ID: 161058e9fab6
Revises: 097e5ee4e4a0
Create Date: 2025-01-30 10:52:29.365535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161058e9fab6'
down_revision: Union[str, None] = '097e5ee4e4a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
