"""Change id_value and id33_value to bytea

Revision ID: 3f19f6dbd231
Revises: cd360c94d2f2
Create Date: 2025-02-05 10:57:57.214320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f19f6dbd231'
down_revision: Union[str, None] = 'cd360c94d2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
