"""Change id_value and id33_value to bytea

Revision ID: 59a4907ca007
Revises: c65fe4874c4c
Create Date: 2025-01-31 15:08:26.010825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a4907ca007'
down_revision: Union[str, None] = 'c65fe4874c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
