"""Change id_value and id33_value to bytea

Revision ID: 6c57f35ab7bc
Revises: 3f19f6dbd231
Create Date: 2025-02-05 11:20:49.446788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c57f35ab7bc'
down_revision: Union[str, None] = '3f19f6dbd231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
