"""Change id_value and id33_value to bytea

Revision ID: 79b74771198a
Revises: d6b20f8d3a16
Create Date: 2025-02-02 15:34:15.275078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b74771198a'
down_revision: Union[str, None] = 'd6b20f8d3a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
