"""Change id_value and id33_value to bytea

Revision ID: 7d82d25c0770
Revises: 38f16e6afed9
Create Date: 2025-01-31 08:30:33.817554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d82d25c0770'
down_revision: Union[str, None] = '38f16e6afed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
