"""Change id_value and id33_value to bytea

Revision ID: 8d39374ae829
Revises: 0cf789d8b400
Create Date: 2025-01-31 09:02:20.917986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d39374ae829'
down_revision: Union[str, None] = '0cf789d8b400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
