"""Change id_value and id33_value to bytea

Revision ID: b3fc76672a9e
Revises: bce3969e4c57
Create Date: 2025-02-19 07:44:54.776194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3fc76672a9e'
down_revision: Union[str, None] = 'bce3969e4c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
