"""Change id_value and id33_value to bytea

Revision ID: bbe6af8b8d20
Revises: 8d39374ae829
Create Date: 2025-01-31 13:07:55.273030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe6af8b8d20'
down_revision: Union[str, None] = '8d39374ae829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
