"""Change id_value and id33_value to bytea

Revision ID: cd360c94d2f2
Revises: 7947f3b2c14a
Create Date: 2025-02-05 10:36:15.300490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd360c94d2f2'
down_revision: Union[str, None] = '7947f3b2c14a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
