"""Change id_value and id33_value to bytea

Revision ID: ddfcca84ddb5
Revises: b3fc76672a9e
Create Date: 2025-02-19 10:33:19.816971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddfcca84ddb5'
down_revision: Union[str, None] = 'b3fc76672a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
