"""Change id_value and id33_value to bytea

Revision ID: e1700a9d1b24
Revises: 6c57f35ab7bc
Create Date: 2025-02-16 21:56:51.958137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1700a9d1b24'
down_revision: Union[str, None] = '6c57f35ab7bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
