"""Change id_value and id33_value to bytea

Revision ID: f8d1c993d05b
Revises: 656af1f17587
Create Date: 2025-02-05 09:20:35.706427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8d1c993d05b'
down_revision: Union[str, None] = '656af1f17587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
