"""Change id_value and id33_value to bytea

Revision ID: 0cf789d8b400
Revises: 7d82d25c0770
Create Date: 2025-01-31 08:52:42.349056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf789d8b400'
down_revision: Union[str, None] = '7d82d25c0770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
