"""Change id_value and id33_value to bytea

Revision ID: 3396cec443af
Revises: e1700a9d1b24
Create Date: 2025-02-16 22:44:30.034537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3396cec443af'
down_revision: Union[str, None] = 'e1700a9d1b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
