"""Change id_value and id33_value to bytea

Revision ID: 3584627daf9a
Revises: ddfcca84ddb5
Create Date: 2025-02-19 10:40:37.006563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3584627daf9a'
down_revision: Union[str, None] = 'ddfcca84ddb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
