"""Change id_value and id33_value to bytea

Revision ID: 6572a6bcb876
Revises: 8e2784d54a7f
Create Date: 2025-01-30 16:16:01.954513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6572a6bcb876'
down_revision: Union[str, None] = '8e2784d54a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
