"""Change id_value and id33_value to bytea

Revision ID: 715415a45a09
Revises: d7cb0007b3d7
Create Date: 2025-01-30 14:36:20.518337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '715415a45a09'
down_revision: Union[str, None] = 'd7cb0007b3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
