"""Change id_value and id33_value to bytea

Revision ID: 8fc6e85775db
Revises: 6572a6bcb876
Create Date: 2025-01-30 16:27:24.952240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc6e85775db'
down_revision: Union[str, None] = '6572a6bcb876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
