"""Change id_value and id33_value to bytea

Revision ID: bd494112f09a
Revises: eedd4e825ad0
Create Date: 2025-01-30 13:27:06.600637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd494112f09a'
down_revision: Union[str, None] = 'eedd4e825ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
