"""Change id_value and id33_value to bytea

Revision ID: d7cb0007b3d7
Revises: bd494112f09a
Create Date: 2025-01-30 13:43:41.991136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7cb0007b3d7'
down_revision: Union[str, None] = 'bd494112f09a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
